channels:
- conda-forge
- defaults

dependencies:
- python=3.7.0
- bokeh
- cartopy
- cython
- descartes
- geopandas
- jupyterlab
- ipykernel
- matplotlib
- netCDF4
- numpy
- pandas
- pip
- scikit-learn
- scipy
- seaborn
- statsmodels
- tqdm
- xarray
- pip:
  - xgboost==1.1.1
name: partmc_mam4